# SPDX-FileCopyrightText: 2019–2026 Pynguin Contributors
#
# SPDX-License-Identifier: MIT

apiVersion: batch/v1
kind: Job
metadata:
  name: pynguin-benchmarks
spec:
  template:
    spec:
      containers:
      - name: prompt-benchmark
        image: ghcr.io/oetgin/pynguin-benchmark:latest
        volumeMounts:
          - name: prompt-benchmark-results
            mountPath: /pynguin/results
        args: ["--to-run=prompt"]
      - name: model-benchmark
        image: ghcr.io/oetgin/pynguin-benchmark:latest
        volumeMounts:
          - name: model-benchmark-results
            mountPath: /pynguin/results
        args: ["--to-run=model"]
      - name: classic-ours-benchmark
        image: ghcr.io/oetgin/pynguin-benchmark:latest
        volumeMounts:
          - name: classic-ours-benchmark-results
            mountPath: /pynguin/results
        args: ["--to-run=classic"]
      - name: classic-base-benchmark
        image: ghcr.io/oetgin/pynguin-base-benchmark:latest
        volumeMounts:
          - name: classic-base-benchmark-results
            mountPath: /pynguin/results
        args: ["--to-run=classic"]
      volumes:
        - name: prompt-benchmark-results
          persistentVolumeClaim:
            claimName: pvc-lberg
        - name: model-benchmark-results
          persistentVolumeClaim:
            claimName: pvc-lberg
        - name: classic-ours-benchmark-results
          persistentVolumeClaim:
            claimName: pvc-lberg
        - name: classic-base-benchmark-results
          persistentVolumeClaim:
            claimName: pvc-lberg
      restartPolicy: Never
      imagePullSecrets:
        - name: theo-ghcr-secret
