# SPDX-FileCopyrightText: 2019–2026 Pynguin Contributors
#
# SPDX-License-Identifier: MIT

apiVersion: batch/v1
kind: Job
metadata:
  name: pynguin-benchmarks
spec:
  template:
    spec:
      containers:
      - name: test-benchmark
        image: ghcr.io/oetgin/pynguin-benchmark-test:latest
        args: ["--to-run=classic"]
        env:
          - name: PYNGUIN_LLM_BASE_URL
            value: "http://ollama.info.unamur.be"
        volumeMounts:
          - name: test-benchmark-results
            mountPath: /pynguin/results
      volumes:
        - name: test-benchmark-results
          persistentVolumeClaim:
            claimName: pvc-lberg
      restartPolicy: Never
      imagePullSecrets:
        - name: theo-ghcr-secret
