# SPDX-FileCopyrightText: 2019–2026 Pynguin Contributors
#
# SPDX-License-Identifier: MIT

apiVersion: batch/v1
kind: Job
metadata:
  name: pynguin-benchmarks
spec:
  template:
    spec:
      containers:
      - name: prompt-benchmark
        image: ghcr.io/oetgin/pynguin-benchmark:latest
        args: ["--to-run=prompt"]
        env:
          - name: PYNGUIN_LLM_BASE_URL
            value: "http://ollama.info.unamur.be"
        volumeMounts:
          - name: benchmark-results
            mountPath: /pynguin/results
      - name: model-benchmark
        image: ghcr.io/oetgin/pynguin-benchmark:latest
        args: ["--to-run=model"]
        env:
          - name: PYNGUIN_LLM_BASE_URL
            value: "http://ollama.info.unamur.be"
        volumeMounts:
          - name: benchmark-results
            mountPath: /pynguin/results
      - name: classic-ours-benchmark
        args: ["--to-run=classic"]
        env:
          - name: PYNGUIN_LLM_BASE_URL
            value: "http://ollama.info.unamur.be"
        image: ghcr.io/oetgin/pynguin-benchmark:latest
        volumeMounts:
          - name: benchmark-results
            mountPath: /pynguin/results
      - name: classic-base-benchmark
        image: ghcr.io/oetgin/pynguin-base-benchmark:latest
        args: ["--to-run=classic"]
        env:
          - name: PYNGUIN_LLM_BASE_URL
            value: "http://ollama.info.unamur.be"
        volumeMounts:
          - name: benchmark-results
            mountPath: /pynguin/results
      volumes:
        - name: benchmark-results
          persistentVolumeClaim:
            claimName: pvc-lberg
      restartPolicy: Never
      imagePullSecrets:
        - name: theo-ghcr-secret
