# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import queue_example as module_0
import array as module_1


def test_case_0():
    int_0 = 3157
    queue_0 = module_0.Queue(int_0)
    assert isinstance(queue_0, module_0.Queue)
    assert queue_0.max == 3157
    assert queue_0.head == 0
    assert queue_0.tail == 0
    assert queue_0.size == 0
    assert isinstance(queue_0.data, module_1.array)
    assert len(queue_0.data) == 3157
    queue_0.dequeue()
    bool_0 = queue_0.empty()
    assert bool_0 is True
    bool_1 = queue_0.full()
    assert bool_1 is False
    bool_2 = queue_0.full()
    assert bool_2 is False
    bool_3 = queue_0.empty()
    assert bool_3 is True
    bool_4 = queue_0.empty()
    assert bool_4 is True
    bool_5 = queue_0.empty()
    assert bool_5 is True
    int_1 = -124
    bool_6 = queue_0.enqueue(int_1)
    assert bool_6 is True
    assert queue_0.tail == 1
    assert queue_0.size == 1
    var_0 = queue_0.dequeue()
    assert var_0 == -124
    assert queue_0.head == 1
    assert queue_0.size == 0
    bool_7 = queue_0.empty()
    assert bool_7 is True


def test_case_1():
    bool_0 = False
    with pytest.raises(AssertionError):
        module_0.Queue(bool_0)


def test_case_2():
    bool_0 = True
    queue_0 = module_0.Queue(bool_0)
    assert isinstance(queue_0, module_0.Queue)
    assert queue_0.max is True
    assert queue_0.head == 0
    assert queue_0.tail == 0
    assert queue_0.size == 0
    assert isinstance(queue_0.data, module_1.array)
    assert len(queue_0.data) == 1
    bool_1 = queue_0.full()
    assert bool_1 is False
    bool_2 = queue_0.empty()
    assert bool_2 is True
    queue_1 = module_0.Queue(bool_0)
    assert queue_1.head == 0
    assert queue_1.tail == 0
    assert queue_1.size == 0
    bool_3 = queue_1.empty()
    assert bool_3 is True
    bool_4 = queue_1.enqueue(bool_3)
    assert bool_4 is True
    assert queue_1.size == 1
    queue_2 = module_0.Queue(bool_0)
    assert queue_2.head == 0
    assert queue_2.size == 0
    var_0 = queue_2.dequeue()
    bool_5 = True
    bool_6 = queue_1.enqueue(var_0)
    assert bool_6 is False
    queue_3 = module_0.Queue(bool_5)
    assert queue_3.head == 0
    assert queue_3.size == 0
    bool_7 = queue_3.empty()
    assert bool_7 is True
    queue_4 = module_0.Queue(bool_5)
    assert queue_4.head == 0
    assert queue_4.size == 0


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 3157
    queue_0 = module_0.Queue(int_0)
    assert isinstance(queue_0, module_0.Queue)
    assert queue_0.max == 3157
    assert queue_0.head == 0
    assert queue_0.tail == 0
    assert queue_0.size == 0
    assert isinstance(queue_0.data, module_1.array)
    assert len(queue_0.data) == 3157
    queue_0.dequeue()
    bool_0 = queue_0.empty()
    assert bool_0 is True
    bool_1 = queue_0.full()
    assert bool_1 is False
    bool_2 = queue_0.full()
    assert bool_2 is False
    queue_1 = module_0.Queue(int_0)
    assert queue_1.head == 0
    assert queue_1.tail == 0
    assert queue_1.size == 0
    bool_3 = queue_1.empty()
    assert bool_3 is True
    bool_4 = queue_1.enqueue(bool_2)
    assert bool_4 is True
    assert queue_1.tail == 1
    assert queue_1.size == 1
    bool_5 = queue_1.full()
    assert bool_5 is False
    bool_6 = queue_1.empty()
    assert bool_6 is False
    bool_7 = queue_0.empty()
    assert bool_7 is True
    var_0 = queue_1.dequeue()
    assert var_0 == 0
    assert queue_1.head == 1
    assert queue_1.size == 0
    bool_8 = queue_1.full()
    assert bool_8 is False
    bool_9 = queue_0.enqueue(bool_2)
    assert bool_9 is True
    assert queue_0.tail == 1
    assert queue_0.size == 1
    bool_10 = queue_1.enqueue(bool_9)
    assert bool_10 is True
    assert queue_1.tail == 2
    assert queue_1.size == 1
    int_1 = -323
    module_0.Queue(int_1)
