version = 1

# If no copyright is present, use MIT License
[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "2019–2026 Pynguin Contributors"
SPDX-License-Identifier = "MIT"
